"""Story-032 tests: star covariance, FR-004 arbitration, diagnostics
e2e, determinism, and the electron-path smoke (ADR-004/006).

Star models are pure-overlap synthetics: the k-mesh is the 2x2x2
Gamma-centred cubic mesh, eigenvectors live on an 8^3 real-space grid
as orthonormal random columns per orbit representative, and the whole
mesh is generated by the S3 axis-permutation action on the grid:

    psi_{g k} = Pi_g psi_k ,   eps_{g k} = eps_k   (star-scalar)

so compute_Mmn overlaps and the band-basis Z are exactly covariant by
construction.  Any implementation that breaks covariance (per-k noise
tie-breaks, asymmetric neighbor handling) shows up as a projector
mismatch in the grid basis.
"""

import numpy as np
import pytest

from lawaf.io.w90 import compute_Mmn, kmesh_nnlist
from lawaf.wannierization.disentangle import (
    InfeasibleWindowError,
    resolve_windows,
    select_subspace,
)

from test_disentangle_mlwf import FIXTURE, _bato3_phonon, _win_ev

NG = 8  # real-space grid per axis


def _s3_ops():
    """The six axis permutations as integer matrices acting on k."""
    from itertools import permutations

    return [
        np.array(perm, dtype=int) for perm in permutations(np.eye(3, dtype=int))
    ]


def _grid_perm(op):
    """Row permutation of the NG^3 grid under a signed integer op.

    Grid points are centred fractions r_i = (i - (NG-1)/2)/NG, mapped as
    r -> op @ r; the grid is invariant under signed permutations.
    """
    coords = np.stack(
        np.meshgrid(*[(np.arange(NG) - (NG - 1) / 2) / NG] * 3, indexing="ij"),
        axis=-1,
    ).reshape(-1, 3)
    target = coords @ op.T  # (r @ op.T)_i = (op r)_i
    # nearest grid point of the permuted coordinates
    idx = np.rint(target * NG + (NG - 1) / 2).astype(int)
    flat = (idx[:, 0] * NG + idx[:, 1]) * NG + idx[:, 2]
    assert np.array_equal(np.sort(flat), np.arange(NG**3)), "grid not closed"
    # Pi_g psi: new[i] = old[orig(i)] where flat[i] = orig index
    perm = np.empty(NG**3, dtype=int)
    perm[flat] = np.arange(NG**3)
    return perm


def _star_model(nband=12, seed=20260830):
    """Covariant synthetic: (kpts, psi, evals, nnlist, wb, mmn, ops).

    Orbit representatives (Gamma, X, M, R) get seeded random orthonormal
    columns; every other mesh point is the Pi_g image of its
    representative with star-scalar energies.
    """
    rng = np.random.default_rng(seed)
    kpts = np.array(
        [
            [0.0, 0.0, 0.0],
            [0.0, 0.5, 0.0], [0.0, 0.0, 0.5], [0.5, 0.0, 0.0],
            [0.0, 0.5, 0.5], [0.5, 0.0, 0.5], [0.5, 0.5, 0.0],
            [0.5, 0.5, 0.5],
        ]
    )
    # per-representative spectra (12 bands); X carries a pair degenerate
    # well inside rtol yet machine-distinct (straddle material)
    eps = {
        (0, 0, 0): [0.00, 0.90, 1.30, 1.30, 2.10, 2.10, 3.40, 3.55,
                    3.55, 4.20, 4.70, 5.10],
        (0, 0, 1): [-0.20, 0.80 + 1e-14, 0.80 + 3e-14, 1.90, 2.40,
                    2.40, 3.30, 3.60, 3.90, 4.40, 4.80, 5.20],
        (0, 1, 1): [0.15, 0.95, 0.95, 2.05, 2.85, 2.85, 3.45, 3.70,
                    3.70, 4.30, 4.90, 5.30],
        (1, 1, 1): [0.30, 0.30, 1.40, 2.20, 2.60, 2.60, 3.50, 3.80,
                    3.80, 4.35, 4.75, 5.15],
    }
    ops = _s3_ops()

    def key(k):
        return tuple(int(round(x)) for x in np.rint(np.mod(k, 1.0)) * 2 % 2)

    # representative of each mesh point: op mapping rep -> k
    reps = {}
    for ik, k in enumerate(kpts):
        for rep in eps:
            rep_k = np.array(rep) / 2.0
            for g in ops:
                if np.allclose(np.mod(rep_k @ g.T, 1.0), np.mod(k, 1.0)):
                    reps[ik] = (rep, g)
                    break
            if ik in reps:
                break
        assert ik in reps, f"no representative for k={k}"

    psi = np.zeros((len(kpts), NG**3, nband), dtype=complex)
    evals = np.zeros((len(kpts), nband))
    for rep, columns in eps.items():
        q, _ = np.array(rep) / 2.0, None
        base = rng.normal(size=(NG**3, nband)) + 1j * rng.normal(
            size=(NG**3, nband)
        )
        columns_rep, _ = np.linalg.qr(base)
        for ik, k in enumerate(kpts):
            rep_k, g = reps[ik]
            if rep_k != rep:
                continue
            perm = _grid_perm(g)
            psi[ik] = columns_rep[perm, :]
            evals[ik] = eps[rep_k]

    nnlist, nncell, _bvecs, wb = kmesh_nnlist(kpts, np.eye(3))
    mmn = compute_Mmn(psi, nnlist, nncell)
    return kpts, psi, evals, nnlist, np.asarray(wb), mmn, ops, reps


def _projector_grid(psi_k, U_k):
    """Grid-basis projector of the selected columns."""
    cols = psi_k @ U_k
    return cols @ cols.conj().T


def _apply_op_grid(P, perm):
    return P[np.ix_(perm, perm)]


class TestStarCovariance:
    """FR-005 / PRD success 4: selected subspaces transform covariantly."""

    def test_projector_equality_on_stars(self):
        kpts, psi, evals, nnlist, wb, mmn, ops, reps = _star_model()
        nk = len(kpts)
        feasible, frozen = resolve_windows(
            kpts, evals, 3, win_min=-0.3, win_max=2.0,
            froz_min=-0.3, froz_max=0.5,
        )
        res = select_subspace(
            mmn, nnlist, wb, feasible, frozen, 3, eigvals=evals
        )
        # energy windows decide whole blocks everywhere except Gamma's
        # 1.30 pair (cut block, Z arbitration inside it)
        P = [_projector_grid(psi[ik], res.U_sel[ik]) for ik in range(nk)]

        # every star arm's selected projector must be the Pi_g image of
        # its orbit representative (construction: psi_ik = psi_rep[perm]
        # with perm = _grid_perm(g), so P_rep = P_ik[inv, inv]).
        # A per-arm noise tie-break or asymmetric neighbor handling
        # makes the mapped projectors disagree.  (Full homomorphic
        # orbit closure under composite ops -- w90 ``sitesym`` territory
        # -- is the documented follow-up, not an AC.)
        for ik in range(nk):
            rep, g = reps[ik]
            rep_k = np.array(rep) / 2.0
            jrep = int(np.argmin(
                np.linalg.norm(
                    np.mod(kpts - rep_k + 0.5, 1.0) - 0.5, axis=1
                )
            ))
            inv = np.argsort(_grid_perm(g))
            Prep = _apply_op_grid(P[ik], inv)
            err = np.linalg.norm(Prep - P[jrep])
            assert err < 1e-10, (
                f"star covariance broken: k={ik} {kpts[ik]} vs rep "
                f"{jrep} {kpts[jrep]}\n|dP|={err:.3e}"
            )

    def test_cut_block_content_covariant(self):
        """Gamma's cut pair must be arbitrated little-group covariantly:
        the whole-mesh projector comparison above includes Gamma (fixed
        by S3), which pins the arbitrated pair projector to commute with
        the S3 grid action; verify it is not identity-symmetric noise."""
        kpts, psi, evals, nnlist, wb, mmn, ops, reps = _star_model()
        feasible, frozen = resolve_windows(
            kpts, evals, 3, win_min=-0.3, win_max=2.0,
            froz_min=-0.3, froz_max=0.5,
        )
        res = select_subspace(
            mmn, nnlist, wb, feasible, frozen, 3, eigvals=evals
        )
        # Gamma: frozen band 0, energy-fixed band 1 (0.90 singlet), and
        # the Z-arbitrated cut column from the 1.30 pair {2, 3}
        U0 = res.U_sel[0]
        support = np.abs(U0).argmax(axis=0)
        assert support[0] == 0
        assert support[1] == 1
        assert support[2] in (2, 3)
        # the arbitrated column may mix only inside the {2,3} pair
        outside = np.abs(U0[[0, 1] + list(range(4, len(U0))), 2:3]).max()
        assert outside < 1e-12


class TestStraddlingDegeneracy:
    """FR-004 + FR-005: a window edge never splits a degenerate block
    silently; the decision is identical on every star arm."""

    def test_inner_edge_expands_to_whole_block_on_all_arms(self):
        kpts, psi, evals, nnlist, wb, mmn, ops, reps = _star_model()
        feasible, frozen = resolve_windows(
            kpts, evals, 3, win_min=-0.3, win_max=2.0,
            froz_min=-0.3, froz_max=0.80 + 2e-14,  # inside the X pair
        )
        nk_total = len(kpts)
        x_arms = [ik for ik in range(nk_total)
                  if abs(evals[ik][0] - (-0.2)) < 1e-12]
        for ik in x_arms:
            if abs(evals[ik][0] - (-0.2)) < 1e-12:  # the three X arms
                assert frozen[ik] == (0, 1, 2), (
                    f"k={ik} frozen {frozen[ik]}: straddled pair must be "
                    "frozen whole"
                )
                assert feasible[ik] == (0, 1, 2, 3)
        res = select_subspace(
            mmn, nnlist, wb, feasible, frozen, 3, eigvals=evals
        )
        # star-consistent: whole-block frozen content is covariant.
        # the representative arm carries k = rep/2 exactly
        P = [_projector_grid(psi[ik], res.U_sel[ik]) for ik in range(nk_total)]
        for ik in x_arms:
            rep, g = reps[ik]
            rep_k = np.array(rep) / 2.0
            jrep = int(np.argmin(
                np.linalg.norm(np.mod(kpts - rep_k + 0.5, 1.0) - 0.5, axis=1)
            ))
            # construction: psi_ik = psi_rep[perm, :] (rows forwarded),
            # so P_arm = P_rep[perm, perm] and the rep projector is the
            # inverse permutation of the arm projector
            perm = _grid_perm(g)
            inv = np.argsort(perm)
            Prep = _apply_op_grid(P[ik], inv)
            err = np.linalg.norm(Prep - P[jrep])
            assert err < 1e-10, f"X arm k={ik} vs rep arm {jrep}: {err:.3e}"

    def test_outer_edge_expands_to_whole_block(self):
        kpts, psi, evals, nnlist, wb, mmn, ops, reps = _star_model()
        x = [ik for ik in range(len(kpts))
             if abs(evals[ik][0] - (-0.2)) < 1e-12]
        feasible, frozen = resolve_windows(
            kpts[x], evals[x], 3, win_min=-0.3,
            win_max=0.80 + 2e-14,  # outer edge inside the X pair
        )
        for row in range(len(x)):
            assert feasible[row] == (0, 1, 2), feasible[row]

    def test_oversized_expansion_raises_named_error(self):
        kpts, psi, evals, nnlist, wb, mmn, ops, reps = _star_model()
        with pytest.raises(InfeasibleWindowError, match="degenerate block"):
            resolve_windows(
                kpts, evals, 2, win_min=-0.3, win_max=2.0,
                froz_min=-0.3, froz_max=0.80 + 2e-14,
            )


class TestDiagnosticsEndToEnd:
    """FR-007: SelectionResult diagnostics reach the user-facing object
    through the downfolder (not only the raw function)."""

    @pytest.mark.slow
    @pytest.mark.skipif(not FIXTURE.exists(), reason="BaTiO3 fixture not found")
    def test_bato3_selection_diagnostics(self, tmp_path):
        from lawaf.interfaces.phonopy import phonon_downfolder as pdf

        phonon = _bato3_phonon()
        params = dict(
            method="mlwf", nwann=3, anchors={(0.0, 0.0, 0.0): (0, 1, 2)},
            use_proj=True, weight_func="unity", kmesh=(2, 2, 2),
            gamma=True,
            dis_win_min=_win_ev(-210), dis_win_max=_win_ev(150),
            dis_froz_min=_win_ev(-210), dis_froz_max=_win_ev(-120),
            dis_min_svd=0.0,  # intrinsically singular content (memo F2)
        )
        df = pdf.PhonopyDownfolder(phonon=phonon, params=params)
        lwf = df.downfold(
            output_path=str(tmp_path), write_hr_nc=None, write_hr_txt=None
        )
        # FR-007: the diagnostics reach the user-facing result object,
        # not only the internal builder (review R4)
        sel = getattr(lwf, "selection", None)
        assert sel is not None
        assert sel is df.builder.selection
        nk, nntot = len(df.builder.kpts), sel.pair_svd_min.shape[1]
        assert sel.pair_svd_min.shape == sel.pair_svd_mean.shape == (nk, nntot)
        assert sel.pair_svd_mean.min() > 0.0
        assert sel.z_gap.shape == (nk,)
        # non-arbitrated ks carry inf; arbitrated ks a finite gap
        assert not np.isnan(sel.z_gap).any()
        assert sel.n_iter >= 1
        assert len(sel.subspace_change_trace) == sel.n_iter
        assert set(sel.guidance) >= {
            "tie_snapped", "budget_exhausted", "sources"}
        assert sel.guidance["sources"]["window_bands"] is False
        assert isinstance(sel.omega_i_selection, float)
        assert np.isfinite(sel.omega_i_selection)


class TestNacResultDiagnostics:
    """Review R4 round-2: NACPhonopyDownfolder has its own NACLWF
    assembly and must carry the selection/spreads diagnostics too."""

    @pytest.mark.slow
    @pytest.mark.skipif(not FIXTURE.exists(), reason="BaTiO3 fixture not found")
    def test_nac_lwf_carries_selection(self, tmp_path):
        from pathlib import Path

        from lawaf.interfaces.phonopy import phonon_downfolder as pdf

        fdir = FIXTURE.parent
        if not (fdir / "BORN").exists():
            pytest.skip("BORN file not available")
        params = dict(
            method="mlwf", nwann=3, anchors={(0.0, 0.0, 0.0): (0, 1, 2)},
            use_proj=True, weight_func="unity", kmesh=(2, 2, 2),
            gamma=True,
            dis_win_min=_win_ev(-210), dis_win_max=_win_ev(150),
            dis_froz_min=_win_ev(-210), dis_froz_max=_win_ev(-120),
            dis_min_svd=0.0,  # intrinsically singular content (memo F2)
        )
        df = pdf.NACPhonopyDownfolder(
            phonopy_yaml=str(fdir / "phonopy_params.yaml"),
            mode="DM", params=params, nac_params={"method": "wang"},
            born_filename=str(fdir / "BORN"),
        )
        lwf = df.downfold(
            output_path=str(tmp_path), write_hr_nc=None, write_hr_txt=None
        )
        assert getattr(lwf, "selection", None) is not None
        assert lwf.selection is df.builder.selection
        assert lwf.selection.guidance["sources"]["window_bands"] is False
        assert np.isfinite(lwf.spreads["omega"])


class TestDeterminism:
    """NFR-002: two identical downfolder runs are bitwise identical."""

    @pytest.mark.slow
    @pytest.mark.skipif(not FIXTURE.exists(), reason="BaTiO3 fixture not found")
    def test_bitwise_identical_runs(self):
        from lawaf.interfaces.phonopy import phonon_downfolder as pdf

        def one_run():
            phonon = _bato3_phonon()
            params = dict(
                method="mlwf", nwann=3, anchors={(0.0, 0.0, 0.0): (0, 1, 2)},
                use_proj=True, weight_func="unity", kmesh=(2, 2, 2),
                gamma=True,
                dis_win_min=_win_ev(-210), dis_win_max=_win_ev(150),
                dis_froz_min=_win_ev(-210), dis_froz_max=_win_ev(-120),
                dis_min_svd=0.0,
            )
            df = pdf.PhonopyDownfolder(phonon=phonon, params=params)
            df._prepare_data()
            df.atoms = df.model.atoms
            df.builder.prepare()
            df.builder.get_Amn()
            _w, H, _e = df.builder.get_wannk_and_Hk()
            return df.builder, np.asarray(H)

        b1, h1 = one_run()
        b2, h2 = one_run()
        assert np.array_equal(b1.selection.U_sel, b2.selection.U_sel)
        assert np.array_equal(h1, h2)
        for key in b1.spreads:
            v1, v2 = b1.spreads[key], b2.spreads[key]
            assert np.array_equal(v1, v2), key


class TestElectronPathSmoke:
    """FR-008: selection on a non-phonopy orthogonal model through the
    shared eigenvector interface (W90-HR fixture)."""

    SMO = None

    @classmethod
    def _folder(cls):
        from pathlib import Path

        smo = (
            Path(__file__).parent.parent
            / "example" / "Wannier90" / "SMO_wannier"
        )
        if not (smo / "abinito_w90_down_hr.dat").exists():
            pytest.skip("SMO example data not available")
        return smo

    @pytest.mark.slow
    def test_w90_hr_selection_engages(self):
        from lawaf import W90Downfolder

        smo = self._folder()
        df = W90Downfolder(
            folder=str(smo), prefix="abinito_w90_down",
            params=dict(
                method="mlwf", kmesh=(4, 4, 4), nwann=5,
                weight_func="Gauss", weight_func_params=(10.0, 3.0),
                use_proj=False, orthogonal=True,
                dis_win_min=-1.0, dis_win_max=6.0,
                dis_froz_min=-1.0, dis_froz_max=2.3,
                mlwf_tol=1e-12, mlwf_max_iter=200,
            ),
        )
        df._prepare_data()
        df.atoms = df.model.atoms
        df.builder.prepare()
        df.builder.get_Amn()
        _w, H, _e = df.builder.get_wannk_and_Hk()
        b = df.builder
        assert b.selection is not None, "selection must engage (nband 14 > 5)"
        assert b.nband > b.nwann
        H = np.asarray(H)
        assert H.shape == (len(b.kpts), 5, 5)
        assert np.isfinite(H).all()
        assert np.isfinite(b.spreads["omega"])
        assert len(b.mlwf_history) >= 1
        # on-mesh branch eigenvalues inside the window bounds
        ev = np.linalg.eigvalsh(H)
        assert ev.min() > -1.5 and ev.max() < 6.5
